Adição das soluções de travel grid e fibonnaci
nahumsa/PROVOC-Python pull request #3
Opened 2021-05-20 18:48 UTC by KakeyaK

Programação dinâmica

2021-05-20 20:42 UTC, mauromoledo commented
@KakeyaK 

Muito bom seu código, só acho que faltou implementar uma opção de tocar música hacker.

fiz um pull resqust também, se você quiser comentar sobre ele: #4

2021-05-20 20:45 UTC, mauromoledo requested changes
@KakeyaK 
Fui em files changed e fui clicando em revisado, ai agora essa aqui é uma revisão sobre os seus códigos.

Ai eu aprovei seu código

2021-05-20 20:49 UTC, mauromoledo requested changes
Fiz alguma sugestões no escopo do seu código

2021-05-20 20:49 UTC, mauromoledo commented on solucoes/kim/CBPF - Fibonnaci.py
> +    unittest.main(argv=['first-arg-is-ignored'], exit=False)
Aqui nesse código deveria ter uma opção de tocar música hacker.

2021-05-20 20:49 UTC, mauromoledo commented on solucoes/kim/CBPF - Travel Grid.py
> +    unittest.main(argv=['first-arg-is-ignored'], exit=False)
Tá ótimo, só acho que devia tirar o teste para ficar que nem o meu pq eu esqueci de por

2021-05-20 20:49 UTC, mauromoledo commented on solucoes/kim/CBPF - Travel Grid.py
> +
comentário em outra linha

2021-05-20 20:49 UTC, mauromoledo commented on solucoes/kim/CBPF - Fibonnaci.py
> +## Fibonacci rescursivo com memorização
hmmm

2021-05-20 20:51 UTC, mauromoledo approved these changes
Aprovado

2021-05-20 20:52 UTC, mauromoledo reviewed
Comentário geral sobre o seu código

2021-06-01 17:53 UTC, merged

2021-06-01 20:02 UTC, KakeyaK commented on solucoes/kim/CBPF - Fibonnaci.py
> +    unittest.main(argv=['first-arg-is-ignored'], exit=False)
JKKKKKKKKKKKKKKKK